docs/3/configuration-changes.md
In insp3, SASL's `target` field is now required. This change broke SASL in inspircd-docker during the upgrade to insp3 and might be worth mentioning on this page.
=> document SASL target change

docs/3/modules/services_account.md
The channel mode is wrong - [it's `+R` and not `+L`][1]
I'm also curious whether it's intentional that the channel mode `regdeaf` collides with `reginvite` (both are `+R` - probably a bug?)
I've refrained from also fixing `regdeaf` because of that.
[1]: https://github.com/inspircd/inspircd/blob/7ad534c1af4578a0d46742c4b6b00a5a33afb63f/src/modules/m_services_account.cpp#L162]
=> Change services_account channel mode from L to R

docs/3/modules/ssl_openssl.md
This functionality is enabled by default since 3.0.0a4, reference inspircd/inspircd@ce78049.
=> 3.0/ssl_openssl: Remove mention of an obsolete #define.

docs/2/modules/index.md, docs/2/modules/sslinfo.md, docs/3/modules/index.md, docs/3/modules/sslinfo.md, docs/3/modules/sslmodes.md
- Describe `sslinfo` a little more so users know it's more than just a command.
- Add the sslqueries user mode to `sslmodes` description.
=> Slight improvments to the sslinfo and sslmodes

docs/2/configuration/_connect.md, docs/3/configuration/_connect.md
The description here didn't match that of the example conf. From my understanding of the code, the example conf is correct, so correcting it here. Also added the example conversion from the example conf to aid in understanding it.
=> Improve the description of 'connect:commandrate'.

docs/2/configuration/_insane.md
The yes/no flags for each ban type are used to bypass the insane ban check; not whether to apply the check.
This actually caused me to change my network's config during the upgrade from v2 to v3, whoops. :smile:
Reference: [Example Conf](https://github.com/inspircd/inspircd/blob/insp3/docs/conf/inspircd.conf.example#L1002-L1028)
Reference: [InsaneBan::MatchesEveryone](https://github.com/inspircd/inspircd/blob/insp3/src/coremods/core_xline/core_xline.cpp#L32-L33)
=> Correct the descriptions for the insane tag.

docs/3/modules/pgsql.md, docs/3/modules/sqlauth.md
Came across these while reading docs:
- default port for pgsql is 5432 (3306 is mysql's)
- column is not required in <sqlauth>
=> Minor doc improvements

docs/3/commands/_cmd_servlist.md
Fixes linter+Github Checks error.
```
$ ./tools/find-whitespace 
/inspircd-docs/docs/3/commands/_cmd_servlist.md has three or more consecutive empty lines!
1 problems!
```
=> Fix linter error about 3 consecutive newlines

docs/security/2019-01.md, docs/security/2019-02.md, docs/security/2020-01.md
These CVE IDs were recently assigned by MITRE to track the vulnerabilities disclosed in InspIRCd Security Advisories 2019-01, 2019-02, and 2020-01. We should update these advisories to reference their CVE IDs.
It may take a day or so before the CVE pages will load on the MITRE website as the IDs were only just assigned today.
My hope is by obtaining CVE IDs for these vulnerabilities we can more quickly get these security patches into downstream Linux distributions.
=> Add CVE identifiers to security advisories

docs/3/configuration/_oper.md, docs/3/modules/sqloper.md
Explains how the sqloper query is used to create opers, with addition info on the oper configuration options.
=> Sqloper doc additions

docs/3/modules/index.md
Fixes a typo that confused me for a second when going through the docs.
=> Fix usermode g description on modules index page

.github/workflows/pr-checks.yml, tools/find-broken-redirects
CI will fail until you merge GH-80, because this script depends on the new format of `mkdocs.yml` (`plugins:` being a Hash rather than an Array)
=> Add a script to find broken redirects.

docs/3/modules/hostchange.yml
configurations states `ports` but the example has `port`
It could also maybe do an example of how to list multiple ports
=> Fixed exmaple in <hostchange>

docs/3/installation/ubuntu.md
Previous paths were out of date and referenced the /usr folder, which is no longer in use..
=> Update paths to Data and Log files

docs/3/modules/alias.yml
Missing change from ed36f2fccb4a0815e4f0edce66fcf37b61ae4742.
=> alias: Remove redundant '<'

docs/3/channel-modes.md
I was looking for a way to set these modes, and was at a loss when I couldn't find them with ctrl-f on the page.
Hopefully this should help future readers.
=> Mention the 'customprefix' module in the chmodes table

docs/3/breaking-changes.md, docs/3/change-log.md, docs/3/channel-modes.md, docs/3/commands/index.md, docs/3/configuration/index.md, docs/3/configuration/useful-snippets.md, docs/3/extended-bans.md, docs/3/installation/centos.md, docs/3/installation/debian.md, docs/3/installation/index.md, docs/3/installation/rocky.md, docs/3/installation/source.md, docs/3/installation/ubuntu.md, docs/3/installation/windows-source.md, docs/3/installation/windows.md, docs/3/module-manager.md, docs/3/modules/index.md, docs/3/snomasks.md, docs/3/user-modes.md, mkdocs_inspircd/__init__.py
This will allow using the same files between v3 and v4 docs without copying the whole file (just a symlink)
=> Dynamically fill version in page titles

docs/3/modules/spanningtree.yml, docs/4/modules/spanningtree.yml
The example text says
> Listens for TLS encrypted server connections on the *:7002 endpoint with a TLS (SSL) profile named "Servers":
but we used port `7003` in the shown example below.
=> Fix usage example

docs/3/configuration/_bind.yml, docs/4/configuration/_bind.yml
The "port" attribute allows for port ranges, too.
=> Show that "port" attribute of "bind" tag also supports port ranges

docs/4/modules/securelist.yml
This removes the extra `fakechans="5"`.
=> securelist.yml: duplicate line in example

docs/3/modules/haproxy.yml
Small change to the documentation on the HAproxy module to explicitly state that it supports version 2 of the protocol.
=> Add note about the version of the HAproxy protocol supported
